version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80"

packages: [php8.0-curl, php8.0-http, php8.0-raphf, php8.0-redis, php8.0-sqlite, whois]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"
    - "sudo mkdir /config && sudo chmod 777 /config"


  run:
  dev:
  test:


